-- Enable pg_cron extension if not already enabled (requires superuser, usually enabled in Supabase dashboard)
-- create extension if not exists pg_cron;

-- 1. Create 'zones' table
create table if not exists public.zones (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  lat double precision not null,
  lon double precision not null,
  radius double precision not null, -- in KM
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create 'zone_history' table
create table if not exists public.zone_history (
  id bigint generated by default as identity primary key,
  zone_id bigint references public.zones(id) on delete cascade not null,
  recorded_at timestamp with time zone default timezone('utc'::text, now()) not null,
  avg_price numeric,
  avg_m2_price numeric,
  avg_rooms numeric,
  avg_bathrooms numeric,
  avg_roi numeric,
  property_count integer,
  min_price numeric,
  max_price numeric
);

-- 3. RLS Policies

-- Enable RLS
alter table public.zones enable row level security;
alter table public.zone_history enable row level security;

-- Zones Policies
create policy "Users can view their own zones"
  on public.zones for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own zones"
  on public.zones for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own zones"
  on public.zones for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own zones"
  on public.zones for delete
  using ( auth.uid() = user_id );

-- History Policies (View only for users, system inserts)
create policy "Users can view history of their own zones"
  on public.zone_history for select
  using ( exists (
    select 1 from public.zones
    where zones.id = zone_history.zone_id
    and zones.user_id = auth.uid()
  ));

-- 4. Stored Procedure for Daily Calculation
-- This function will be called by pg_cron or an external trim
create or replace function calculate_daily_zone_stats()
returns void
language plpgsql
security definer
as $$
declare
  z record;
  stats record;
begin
  -- Loop through all zones
  for z in select * from public.zones loop
    
    -- Calculate stats for this zone
    -- We use a lateral join thinking or just a direct query for simplicity within the loop
    -- Using Haversine formula for distance: 6371 * acos(...)
    
    select 
      count(*) as p_count,
      avg(sale_price) as avg_p,
      avg(sale_price / nullif(m2, 0)) as avg_m2,
      avg(rooms) as avg_r,
      avg(bathrooms) as avg_b,
      min(sale_price) as min_p,
      max(sale_price) as max_p
      -- avg_roi calculation is complex to do in pure SQL if logic is in JS, 
      -- but we can approximate it or calculate it if rent_price exists
    into stats
    from public.datahouse
    where 
      (
        6371 * acos(
          cos(radians(z.lat)) * cos(radians(lat)) * cos(radians(lon) - radians(z.lon)) +
          sin(radians(z.lat)) * sin(radians(lat))
        )
      ) <= z.radius;

    -- Insert into history if properties found
    if stats.p_count > 0 then
      insert into public.zone_history (
        zone_id,
        avg_price,
        avg_m2_price,
        avg_rooms,
        avg_bathrooms,
        property_count,
        min_price,
        max_price,
        avg_roi -- We'll leave this null or add logic if needed
      ) values (
        z.id,
        stats.avg_p,
        stats.avg_m2,
        stats.avg_r,
        stats.avg_b,
        stats.p_count,
        stats.min_p,
        stats.max_p,
        0 -- Placeholder for ROI, or calculate average yield if rent_price available: avg((rent_price * 12) / sale_price) * 100
      );
      
      -- Update refined ROI if possible
      -- update public.zone_history set avg_roi = (select avg((rent_price * 12) / nullif(sale_price,0)) * 100 from datahouse ... )
    end if;
    
  end loop;
end;
$$;

-- 5. Schedule Cron Job (Commented out as strict permissions might be needed)
-- select cron.schedule('0 1 * * *', $$select calculate_daily_zone_stats()$$);
